package ejercicio2;

import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Rafael
 */
public class windo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(windo.class.getName());

    /**
     * Creates new form windo
     */
    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    
    public windo() {
        initComponents();
        Ventana();
    }

    public void Ventana() {

        ImageIcon imagen = new ImageIcon(getClass().getResource("/assets/fondosuper.jpg"));
        JLabel labelImagen = new JLabel(imagen);
        labelImagen.setBounds(0, 0, 800, 600);
        dtpEscritorio.add(labelImagen);
        add(dtpEscritorio);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpEscritorio = new javax.swing.JDesktopPane();
        MenuBarNavigator = new javax.swing.JMenuBar();
        administracionMenu = new javax.swing.JMenu();
        agregarMenuItem = new javax.swing.JMenuItem();
        modificarMenuItem = new javax.swing.JMenuItem();
        eliminarMenuItem = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        nombreMenuItem = new javax.swing.JMenuItem();
        precioMenuItem = new javax.swing.JMenuItem();
        rubroMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(875, 680));
        setMinimumSize(new java.awt.Dimension(554, 554));
        setResizable(false);

        javax.swing.GroupLayout dtpEscritorioLayout = new javax.swing.GroupLayout(dtpEscritorio);
        dtpEscritorio.setLayout(dtpEscritorioLayout);
        dtpEscritorioLayout.setHorizontalGroup(
            dtpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        dtpEscritorioLayout.setVerticalGroup(
            dtpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        administracionMenu.setText("Administración");

        agregarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/agregar.png"))); // NOI18N
        agregarMenuItem.setText("Agregar productos");
        agregarMenuItem.addActionListener(this::agregarMenuItemActionPerformed);
        administracionMenu.add(agregarMenuItem);

        modificarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/modi.png"))); // NOI18N
        modificarMenuItem.setText("Modificar produtos");
        modificarMenuItem.addActionListener(this::modificarMenuItemActionPerformed);
        administracionMenu.add(modificarMenuItem);

        eliminarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/unaX.png"))); // NOI18N
        eliminarMenuItem.setText("Eliminar productos");
        eliminarMenuItem.addActionListener(this::eliminarMenuItemActionPerformed);
        administracionMenu.add(eliminarMenuItem);

        MenuBarNavigator.add(administracionMenu);

        consultasMenu.setText("Consultas");

        nombreMenuItem.setText("Consulta por nombre");
        nombreMenuItem.addActionListener(this::nombreMenuItemActionPerformed);
        consultasMenu.add(nombreMenuItem);

        precioMenuItem.setText("Consulta por precio");
        precioMenuItem.addActionListener(this::precioMenuItemActionPerformed);
        consultasMenu.add(precioMenuItem);

        rubroMenuItem.setText("Consulta por rubro");
        rubroMenuItem.addActionListener(this::rubroMenuItemActionPerformed);
        consultasMenu.add(rubroMenuItem);

        MenuBarNavigator.add(consultasMenu);

        setJMenuBar(MenuBarNavigator);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        consultanombre ve  = new consultanombre();
        ve.setVisible(true);
        dtpEscritorio.add(ve);
        dtpEscritorio.moveToFront(ve);
    }//GEN-LAST:event_nombreMenuItemActionPerformed

    private void agregarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        agregar va  = new agregar(listaProductos);
        va.setVisible(true);
        dtpEscritorio.add(va);
        dtpEscritorio.moveToFront(va);
    }//GEN-LAST:event_agregarMenuItemActionPerformed

    private void eliminarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        eliminar vistaEliminar = new eliminar();
        vistaEliminar.setVisible(true);
        dtpEscritorio.add(vistaEliminar);
        dtpEscritorio.moveToFront(vistaEliminar);
    }//GEN-LAST:event_eliminarMenuItemActionPerformed

    private void rubroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubroMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        consultarubro ve = new consultarubro();
        ve.setVisible(true);
        dtpEscritorio.add(ve);
        dtpEscritorio.moveToFront(ve);
    }//GEN-LAST:event_rubroMenuItemActionPerformed

    private void precioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        consultaprecio ve = new consultaprecio();
        ve.setVisible(true);
        dtpEscritorio.add(ve);
        dtpEscritorio.moveToFront(ve);
    }//GEN-LAST:event_precioMenuItemActionPerformed

    private void modificarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMenuItemActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        Modificar modificar = new Modificar();
        modificar.setVisible(true);
        dtpEscritorio.add(modificar);
        dtpEscritorio.moveToFront(modificar);
    }//GEN-LAST:event_modificarMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new windo().setVisible(true));
        
        Producto a = new Producto(5, 2000, 1, "un chupetin", "Comestible");
        Producto b = new Producto(4, 3000, 2, "un alfajor", "Comestible");
        Producto c = new Producto(8, 1500, 3, "un cafe", "Comestible");
        listaProductos.add(a);
        listaProductos.add(b);
        listaProductos.add(c);
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarNavigator;
    private javax.swing.JMenu administracionMenu;
    private javax.swing.JMenuItem agregarMenuItem;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JDesktopPane dtpEscritorio;
    private javax.swing.JMenuItem eliminarMenuItem;
    private javax.swing.JMenuItem modificarMenuItem;
    private javax.swing.JMenuItem nombreMenuItem;
    private javax.swing.JMenuItem precioMenuItem;
    private javax.swing.JMenuItem rubroMenuItem;
    // End of variables declaration//GEN-END:variables
}
